### ISSUE TITLE
[question] 规则书写问题

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/selector#1]
快照：https://gkd-kit.gitee.io/import/12620788

需求：找到广告的关闭按钮

规则1：`TextView[id="com.dongqiudi.news:id/feedback_close"] +(2) RelativeLayout > ImageView`

规则2：`TextView +(2) RelativeLayout > ImageView`

其中，规则2可以正确找到我要的那个节点，但是规则1不行，请教大佬，父节点 TextView 为什么不能添加 `id="com.dongqiudi.news:id/feedback_close"` 进一步限定呢？我认为这样会更精准地找到想要的节点，减少误判，但事实上这样写提示找不到任何节点。

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/selector/assets/38517192/19b67cb8-ec6a-45d6-9c7c-a2207a68a253)

是不是看错了，TextView 的 id 是 `id="com.dongqiudi.news:id/ads_title"`

**Comment by lisonge** [comment]
点击属性面板左侧的文字可以直接快捷复制

![image](https://github.com/gkd-kit/selector/assets/38517192/e9400c98-aeb2-44eb-9cd6-19ef1470adc1)

**Comment by lisonge** [comment]
正确的选择器应该是

```txt
TextView[id="com.dongqiudi.news:id/ads_title"] +(2) RelativeLayout > ImageView[id="com.dongqiudi.news:id/feedback_close"]
```

**Comment by Snoopy1866** [comment]
感谢大佬，确实眼花看错了🤣

**Comment by shanlanCoding** [comment]
> 感谢大佬，确实眼花看错了🤣

这些操作符在哪里能查到学习资料？

**Comment by Snoopy1866** [comment]
https://blog.csdn.net/luanpeng825485697/article/details/77692971

**Comment by lisonge** [comment]
在文档里说明了一下，可以直接看文档

https://github.com/gkd-kit/selector
