### ISSUE TITLE
请问如何选中祖先节点的兄弟节点的子孙节点

### ISSUE THREAD

**Issue by hhuimie** [gkd-kit/selector#12]
比如这个界面, 我想在"精选"页面的时候, 选中第一条微博的博主名
我的想法是先选中"精选"文字的祖先节点, 再找到具体信息流的节点
https://i.gkd.li/import/14338582
比如这个, 就可以找到祖先节点了 `@LinearLayout >4 [text="精选"]`
但是无法选择这个节点的兄弟节点, 就也不知道怎么写下去了 `@LinearLayout >4 [text="精选"] FrameLayout`
![image](https://github.com/gkd-kit/selector/assets/4830177/7cfc698b-02b6-4d1d-8b4c-88c479de91b7)

**Comment by lisonge** [comment]
```txt
matches: [ '[clickable=false] > [text="精选"]', '[vid="a2v"] >7 [vid="ael"]' ]
```
