### ISSUE TITLE
无法通过多层父级选择到 ScrollView 节点

### ISSUE THREAD

**Issue by oumoe** [gkd-kit/selector#13]
示例 https://i.gkd.li/import/12642445
使用 [text="应用有新版本，是否下载？"] <2 * 无法选择到节点。
[text="应用有新版本，是否下载？"] < * < * 可以选中。
通过父级向下选择没有问题。

**Comment by lisonge** [comment]
链接是错的，需要快照链接

**Comment by oumoe** [comment]
> 链接是错的，需要快照链接

已更新链接。

**Comment by lisonge** [comment]
你的 gkd 版本太低了，请更新到最新版本

**Comment by lisonge** [comment]
> 使用 [text="应用有新版本，是否下载？"] <2 * 无法选择到节点。

` A <2 B` 的意思是 `A == B.children[2-1]`

**Comment by oumoe** [comment]
> 你的 gkd 版本太低了，请更新到最新版
目前使用的是 1.7.3

**Comment by lisonge** [comment]
` A < B` 只能选择 B 的直接子节点，如何你想要选择更深层节点应该使用 `<<`

<https://i.gkd.li/i/12642445?gkd=W3RleHQ9IuW6lOeUqOacieaWsOeJiOacrO-8jOaYr-WQpuS4i-i9ve-8nyJdIDw8MiAq>

**Comment by oumoe** [comment]
> ` A < B` 只能选择 B 的直接子节点，如何你想要选择更深层节点应该使用 `<<`
> 
> https://i.gkd.li/i/12642445?gkd=W3RleHQ9IuW6lOeUqOacieaWsOeJiOacrO-8jOaYr-WQpuS4i-i9ve-8nyJdIDw8MiAq

了解，感谢解答。
