### ISSUE TITLE
选择器元素疑问

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/selector#14]
现在存在一个快照如下：
https://i.gkd.li/i/15782476

同时存在两条选择器规则如下：
- `[text!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"]`

- `ImageView <n * TextView <<n * > [name$="ImageView" || name$="Button"][desc="关闭" || (desc=null && text=null)]`

它们分开都可以在在该快照下选择到元素，如下图

![image](https://github.com/gkd-kit/selector/assets/34203474/cf6570d7-453e-46f5-a427-c9bddcde3a87)

当将两条选择器规则合并成一条：

`ImageView <n * TextView <<n * > [name$="ImageView" || name$="Button"][desc="关闭" || (desc=null && text=null)][text!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"]`

即，将第一条合并到第二条后，为最后一个元素添加一个正则表达式限制text，后无法匹配到任何元素。实际上应该可以匹配到text不含时间文本的元素才对。
![image](https://github.com/gkd-kit/selector/assets/34203474/6079fa01-d0b8-4de2-8b8b-f32b4d6acf46)

是我对选择器规则理解有误还是别的问题？

**Comment by aoguai** [comment]
在此快照中 https://i.gkd.li/i/15912956

使用规则

`[(text*="跳过"||text*="跳過")][text!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"]`

可以选中元素：
![image](https://github.com/gkd-kit/selector/assets/34203474/7af002af-4702-4a61-8c36-6f0c4726a391)
在此基础上添加上 desc 的判断，将规则改为

`[(text*="跳过"||text*="跳過")][text!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"][desc!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"]`

则无法获取元素
![image](https://github.com/gkd-kit/selector/assets/34203474/087c7ff4-ae8f-4152-bbd6-c47eb921acbc)

同时已排除 JS 与 Java 导致的正则表达式不同导致的问题，因为该快照就是因为无法触发规则截下来的。

**Comment by lisonge** [comment]
```txt
[(text*="跳过"||text*="跳過")][text!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"][
 desc=null||
 desc!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"]
```

**Comment by aoguai** [comment]
所以意思是 `!=` 和 `!~=` 等操作符使用中 null 都是需要单独处理的逻辑的吗？因为好像遇到null的情况还蛮多的，之前就有过疑问。
同时是不是如果该字段不存在，是不是规则也会无法匹配

**Comment by aoguai** [comment]
因为
`[desc!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"]`
和
`[desc=null || desc!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]"]`

在理解上感觉还是有区别的，第一条只限制desc不能为时间格式文本，但它并没有限制是否为null。
而第二条是明确表明desc可以为null 或 desc不能为时间格式文本

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/selector/assets/38517192/ea2b3d48-f661-4ad8-97c4-ab6234143f05)

**Comment by aoguai** [comment]
所以现阶段无法做到通过正则表达式只限制desc不能为时间格式文本，而不考虑属性是否null。

**Comment by lisonge** [comment]
是的，你想要的格式应该类似 !(a~='xxx')

**Comment by aoguai** [comment]
好的，谢谢。如果可以的话，希望能更新实现，感觉应该挺有用🤔
