### ISSUE TITLE
[documentation] 说明有误？

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/selector#3]
如图，关于 `A <(an+b) B` : A 是 B 的直接子节点, 并且 A.index 满足 an+b-1 是否有误，我理解 <> 都是涉及 depth 的，不应该是 index，而且满足的条件 `an+b-1` 似乎也跟节点 B 没什么关系，a, b 都是常数。
![image](https://github.com/gkd-kit/selector/assets/45487685/9fb2fecb-8381-4d10-836a-be4dcd0895fa)

**Comment by lisonge** [comment]
不是的，`>`, `<`, `+`, `-` 你可以理解为一种查找节点的方向路径，(an+b) 是在这个方向路径上距离 B 的距离

A <(an+b) B 意思就是 A == B.children[an+b-1]
A >(an+b) B 意思就是 A == B.ancestors[an+b-1]
A +(an+b) B 意思就是 A == B.BeforBrothers[an+b-1]
A -(an+b) B 意思就是 A == B.AfterBrothers[an+b-1]

**Comment by lisonge** [comment]
使用 an+b-1 是因为要和类似的 CSS 选择器语义等价

**Comment by Snoopy1866** [comment]
不是很理解，大佬可以帮忙举个例子，就比如这个快照：https://gkd-kit.gitee.io/import/12639800

我需要通过 TextView 找到它的父级 FrameLayout，进而找到 `暂不开启` 这个 Button，

我写的是 `[text*="开启系统推送"] - ImageView <(3) FrameLayout + FrameLayout >(3) Button[text="暂不开启"]`，但是我测试发现这条路径上第3个节点 `FrameLayout` 就找不到了

**Comment by lisonge** [comment]
`ImageView <(3) FrameLayout ` 这里关系搞错了，是直接子节点，不是子孙节点

直接子节点 是一个数组，子孙节点是数组嵌套数组，下面这个才对

```txt
[text*="开启系统推送"] - ImageView < * < * < FrameLayout + FrameLayout >(3) Button[text="暂不开启"]
```

比如这个快照下的 `@Button < LinearLayoutCompat`  是 `暂不开启` 这个按钮

`@Button <2 LinearLayoutCompat` 是 `去开启` 这个按钮

**Comment by shanlanCoding** [comment]
> ```
> (3) Button[text="暂不开启"]
> ```

(3) Button[text="暂不开启"]

请问这个`(3)`是什么作用？

**Comment by lisonge** [comment]
3 是 偏移 单位

https://github.com/gkd-kit/selector/issues/3#issuecomment-1722125809

A >(3) B 意思就是 A == B.ancestors[3-1]

**Comment by shanlanCoding** [comment]
![image](https://github.com/gkd-kit/selector/assets/44717382/9b4c3f7d-4239-41e8-b930-4fd0f6ddea54)

这个联合判断怎么写？实话说，关系选择器那块教程没看明白。
https://gkd-kit.gitee.io/import/12864214

**Comment by lisonge** [comment]
`[text="广告"] < View <2 View - View >2 [text="| 跳过"]`

`[text="广告"] + View >4 [text="| 跳过"]`
