### ISSUE TITLE
点击选择器选择到的多个相同元素某一个

### ISSUE THREAD

**Issue by ffengdoudou** [gkd-kit/selector#7]
gkd选择器选择到多个相同的id,应该如何进行点击其中的某一个,实现类似于 :nth-child()的选择功能.

**Comment by lisonge** [comment]
请给出快照链接以及需要选择的节点

**Comment by lisonge** [comment]
你说的这个功能目前暂不支持，唯一的方法是寻找其祖先节点，然后判断 index

**Comment by ffengdoudou** [comment]
https://i.gkd.li/import/13400979
谢谢你的答复，我的需求是进行点击每一个赞，你能书写一下具体根据索引进行选择的规则嘛？

**Comment by lisonge** [comment]
```txt
LinearLayout[index=1] >3 [id="com.tencent.mobileqq:id/dyw"]
LinearLayout[index=2] >3 [id="com.tencent.mobileqq:id/dyw"]
LinearLayout[index=3] >3 [id="com.tencent.mobileqq:id/dyw"]
```

**Comment by ffengdoudou** [comment]
谢谢！

**Comment by lisonge** [comment]
看起来你的需求应该是 `点击没有点过的赞的图标`，但是显然无障碍节点信息并没有标识这个按钮到底有没有点击过

这个用 gkd 这种静态的无障碍规则其实不太好实现，你可以考虑用 autojs 一类的动态无障碍工具实现

**Comment by ffengdoudou** [comment]
好的谢谢，这个3是什么意思？

**Comment by lisonge** [comment]
查找第3个祖先

**Comment by ffengdoudou** [comment]
谢谢！

**Comment by hhuimie** [comment]
+1, 还是挺需要类似的功能的, nth-child, nth-last-child
