### ISSUE TITLE
这种没有关闭按钮没有啥特征的怎么点击呢

### ISSUE THREAD

**Issue by Invincible-World** [gkd-kit/selector#8]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息

https://i.gkd.li/import/13432426   需要点击中间广告右下角的小叉叉

**Comment by lisonge** [comment]
搭配 quickFind 使用

```txt
 @ImageView < FrameLayout[childCount=1] <3 [childCount=3] <2 [clickable=true][childCount=2] <<4 [id="com.github.eprendre.tingshu:id/ad_container"]
```

**Comment by incubus-ohy** [comment]
可以解释下这个表达式吗  
<< 4 是
<2
是啥意思

**Comment by Invincible-World** [comment]
> 可以解释下这个表达式吗 << 4 是 <2 是啥意思

https://github.com/gkd-kit/selector     这里有文档
