### ISSUE TITLE
选择器元素分析异常

### ISSUE THREAD

**Issue by binw666** [gkd-kit/selector#9]
如图，我在编写规则的时候发现捕获的快照在右边没有对应的部分，不知道应该如何编写这种规则。我的设备没有root和shizuku，不知道对这个有影响吗？
![image](https://github.com/gkd-kit/selector/assets/60505354/53a07c9b-0079-40e6-8cd7-981d7b13fb94)

问题快照：https://i.gkd.li/snapshot/1703001963224

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/selector/assets/38517192/9d5448d0-898e-4d93-8711-8f13011245cb)

**Comment by lisonge** [comment]
> 我在编写规则的时候发现捕获的快照在右边没有对应的部分

这说明该APP的此界面本来就未提供完整的节点信息，这是无解的
